### ISSUE TITLE
Dokumentation verbessern

### ISSUE THREAD

**Issue by cagix** [cagix/pandoc-thesis#26]
- Readme: Kurze Anleitung, was man braucht und wie man das Projekt startet
- Markdown-Files: 
    - Übersetzen des Projekts
    - Erklären der Struktur und Umfänge
    - Hinweise zu bestimmten Markdown-Aspekten
- Bekannte Issues: 
    - Abbildungen in Eisvogel mit `[H]` (kein floating)
    - Probleme mit Overflow am Seitenrand (dann Abbildung verschieben im Text)
    - Listings haben keine Über-/Unterschrift
    - Zitieren in Bildunterschrift/Tabellenüberschrift funktioniert nicht (wirklich? prüfen!)

Alternativ alles im Readme mit zuklappbaren Einheiten (`<details>...</details>`)?

**Comment by cagix** [comment]
Einsatz der GH-Action:


Du brauchst nun eigentlich nur noch 
- Deine Daten: Eine Markdown-Datei (z.B. `mydoc.md`) und ein Bibtex-File (z.B. `refs.bib`)
- einen GH-Workflow wie den unten mit den Namen angepasst

```yaml
on:
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cagix/pandoc-thesis@master
        with:
          srcfile: mydoc.md
          targetfile: foo.pdf
          bibfile: refs.bib
          template: eisvogel
      - uses: actions/upload-artifact@v4
        with:
          path: foo.pdf
          overwrite: true
```
